[package]
name = "rust-basics"
version = "0.1.0"
authors = ["benfurber <ben@fu.rber.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rust-basics"
path = "./src/main.rs"
